# Backup copy
# Generated by Django 5.2.6 on 2025-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('product_type', models.CharField(choices=[('leg', "Tovuq oyog'i"), ('wing', 'Tovuq qanoti'), ('breast', "Tovuq ko'kragi")], max_length=20, verbose_name='Mahsulot turi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsifi')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjudligi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
            options={
                'indexes': [models.Index(fields=['product_type'], name='products_pr_product_cea9e6_idx'), models.Index(fields=['is_available'], name='products_pr_is_avai_c23034_idx'), models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx')],
            },
        ),
    ]
